<?php
/**用户菜单**/
$menuName=array("删除用户账号","增加用户账号","成绩查询","成绩录入","查询班级");
$menuUrl=array("api/delete.php",
				"api/addAccount.php",
				"api/scoreQuery.php",
				"api/scoreInput.php",
				"api/inquireclass.php");
?>